server:
  port: 8083
spring:
  datasource:
    url: jdbc:h2:mem:campaignservicedb
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
