sequenceDiagram
    participant Client
    participant GW as Gateway :8080
    participant US as user-service :8081
    participant LS as layout-service :8082
    participant CS as campaign-service :8083
    participant TS as template-service :8084

    Client->>+GW: GET /api/users/ (Accept: application/hal+json)
    GW->>GW: match route Path=/api/users/**
    GW->>+US: GET /api/users/ (forwarded)
    US->>US: UsersController.getAll()
    US-->>-GW: 200 HAL+JSON {"_embedded":{},"_links":{"self":{"href":"http://localhost:8081/api/users/"}}}
    GW-->>-Client: 200 HAL+JSON

    Client->>+GW: GET /api/layouts/
    GW->>+LS: GET /api/layouts/ (forwarded)
    LS-->>-GW: 200 HAL+JSON {"_embedded":{},"_links":{"self":{"href":"http://localhost:8082/api/layouts/"}}}
    GW-->>-Client: 200 HAL+JSON

    Client->>+GW: GET /api/campaigns/
    GW->>+CS: GET /api/campaigns/ (forwarded)
    CS-->>-GW: 200 HAL+JSON {"_embedded":{},"_links":{"self":{"href":"http://localhost:8083/api/campaigns/"}}}
    GW-->>-Client: 200 HAL+JSON

    Client->>+GW: GET /api/templates/
    GW->>+TS: GET /api/templates/ (forwarded)
    TS-->>-GW: 200 HAL+JSON {"_embedded":{},"_links":{"self":{"href":"http://localhost:8084/api/templates/"}}}
    GW-->>-Client: 200 HAL+JSON
